LEARNING PYTROCH FOR DEEPLEARNING BY: https://www.youtube.com/watch?v=LyJtbe__2i0

Importing tensorflow and checking how many GPUs are working at the moment

## 00. Pytorch Fundamentals
Resources Notebook: https://www.learnpytorch.io/
<br> if you have a question or Git code: https://github.com/mrdbourke/pytorch-deep-learning

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [7]:
!nvidia-smi   

Sat Jun  7 03:11:41 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.07                 Driver Version: 566.07         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   49C    P8              2W /   80W |    1354MiB /   8188MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## INTRODUCTION TO TENSORS
### Creating TENSORS 
pytorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html#data-types

### Scalar Tensors:

In [8]:
# scalar
scalar = torch.tensor(7)  # way to create scalar tensor
scalar

tensor(7)

In [9]:
scalar.ndim # to check the dimension "We know a scalar is no dimesional number"

0

In [10]:
# Get tensor back as python integer
scalar.item()

7

### Vector Tensor

In [11]:
# Vectors
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

### MATRIX

In [14]:
Matrix = torch.tensor([[8,9],[2,3]])
Matrix

tensor([[8, 9],
        [2, 3]])

In [15]:
Matrix.ndim

2

In [16]:
Matrix.shape

torch.Size([2, 2])

### TENSOR

In [17]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])   
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 4, 3])

In [20]:
TENSOR[0]  # If you will write TENSOR[1] it will give an error 

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [21]:
# Creating a tensor with multiple batches
TENSOR1 = torch.tensor([[[1,2,3,4],[3,4,5,4],[5,6,7,4]],
                        [[7,8,9,4],[9,8,7,4],[6,5,4,4]]])

In [22]:
TENSOR1.ndim

3

In [23]:
TENSOR1.shape

torch.Size([2, 3, 4])

In [24]:
print(TENSOR1[0])

TENSOR1[1]

tensor([[1, 2, 3, 4],
        [3, 4, 5, 4],
        [5, 6, 7, 4]])


tensor([[7, 8, 9, 4],
        [9, 8, 7, 4],
        [6, 5, 4, 4]])

### RANDOM TENSORS

Why random tensor ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
<br> Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [25]:
# Create random tensor of size(3,4)
random_tensor = torch.rand(3,6,5) 
random_tensor

tensor([[[0.3424, 0.8233, 0.3077, 0.5862, 0.2074],
         [0.8556, 0.3955, 0.6724, 0.6033, 0.3368],
         [0.1171, 0.6754, 0.9167, 0.6777, 0.6548],
         [0.8525, 0.0119, 0.3297, 0.1421, 0.8200],
         [0.7010, 0.2348, 0.0537, 0.7801, 0.3419],
         [0.6140, 0.4917, 0.3753, 0.9215, 0.5801]],

        [[0.0820, 0.1169, 0.7622, 0.5965, 0.1094],
         [0.0424, 0.0725, 0.0491, 0.9098, 0.8638],
         [0.5681, 0.1167, 0.6110, 0.3409, 0.1904],
         [0.7998, 0.5074, 0.7396, 0.7582, 0.4687],
         [0.0404, 0.4601, 0.7587, 0.1023, 0.8922],
         [0.5180, 0.8615, 0.2620, 0.0298, 0.3325]],

        [[0.3248, 0.3786, 0.2839, 0.6122, 0.0854],
         [0.7689, 0.7025, 0.1905, 0.1943, 0.3201],
         [0.2655, 0.7021, 0.8276, 0.6921, 0.5392],
         [0.6367, 0.7222, 0.3992, 0.8877, 0.7127],
         [0.6475, 0.5381, 0.7487, 0.5572, 0.7693],
         [0.0382, 0.4027, 0.0830, 0.5077, 0.9076]]])

In [26]:
random_tensor.ndim

3

In [27]:
random_tensor[0]

tensor([[0.3424, 0.8233, 0.3077, 0.5862, 0.2074],
        [0.8556, 0.3955, 0.6724, 0.6033, 0.3368],
        [0.1171, 0.6754, 0.9167, 0.6777, 0.6548],
        [0.8525, 0.0119, 0.3297, 0.1421, 0.8200],
        [0.7010, 0.2348, 0.0537, 0.7801, 0.3419],
        [0.6140, 0.4917, 0.3753, 0.9215, 0.5801]])

In [28]:
random_tensor.shape

torch.Size([3, 6, 5])

In [29]:
random_image_tensor = torch.rand(size=(244,244,3)) # height, width , color channel (R,G,B)
# random_image_tensor = torch.rand(244,244,3)  can be written as this 

In [30]:
random_image_tensor.shape

torch.Size([244, 244, 3])

In [31]:
random_image_tensor.ndim

3

### Tensors of zeros and ones

In [32]:
# creating a tensor with zeros
zero_tensor = torch.zeros(3,4)
zero_tensor, zero_tensor.shape, zero_tensor.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]),
 2)

In [33]:
# create a tensor of all ones
one_tensor = torch.ones(3,4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
# checking data type of tensors
print(one_tensor.dtype)
print(random_image_tensor.dtype)
print(random_tensor.dtype)

torch.float32
torch.float32
torch.float32


### Creating a range of tensors and tensor-like

In [35]:
# Use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# using start end and step with arange
one_to_ten = torch.arange(start=1, end=11, step= 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
one_to_ten.ndim

1

In [38]:
# Creating tensors_like
ten_zeros = torch.zeros_like(input= one_to_ten)     #Check you can see that this new tensor is having the same size as one_to_ten tensor
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# Practice of tensor_like and arange()

one_to_thousand = torch.arange(start=1, end=1001, step=2)
one_to_thousand


tensor([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
         29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
         57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,
         85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111,
        113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139,
        141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
        169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195,
        197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219, 221, 223,
        225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251,
        253, 255, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275, 277, 279,
        281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307,
        309, 311, 313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335,
        337, 339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 3

In [40]:
one_to_thousand.size()

torch.Size([500])

In [41]:
#Now creating a tensor of same size as one_to_thousand but of zeros
one_to_thousand_zeros = torch.zeros_like(input=one_to_thousand)
one_to_thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [42]:
one_to_thousand_zeros.size()

torch.Size([500])

# TENSOR DATA TYPES
**Note:** Tensor datatypes is one of the 3 big issues with Pytorch and Deep learning
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [43]:
# Float32 tensor
float_32_tensor = torch.tensor([0.1,34,5], dtype=torch.float32, device=None,requires_grad=False)
float_32_tensor

tensor([ 0.1000, 34.0000,  5.0000])

In [44]:
float_32_tensor.dtype

torch.float32

In [45]:
# Now changing data type of float32tensor into float16tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([ 0.1000, 34.0000,  5.0000], dtype=torch.float16)

In [46]:
# lets see if we can multiple two different data type tensors
(float_16_tensor*float_32_tensor)

tensor([9.9976e-03, 1.1560e+03, 2.5000e+01])

In [47]:
# Create integer type tensor
int_32_tensor = torch.tensor([3,2,4], dtype=torch.int32)
int_32_tensor

tensor([3, 2, 4], dtype=torch.int32)

In [48]:
# Now check if we can multiply float and int
float_16_tensor*int_32_tensor

tensor([ 0.2998, 68.0000, 20.0000], dtype=torch.float16)

### Getting information from tensors
1. Tensors not right datatypes - To get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - To get shape from tensor, can use tensor.shape
3. Tensors not on the right device - To get device from tensor, can use tensor.device

In [49]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9253, 0.4396, 0.5016, 0.1227],
        [0.7058, 0.8060, 0.4502, 0.6230],
        [0.9177, 0.2869, 0.2333, 0.1330]])

In [50]:
# Find out details about some_tensor
print(f"Data Type of somme_tensor:  {some_tensor.dtype}")
print(f"Shape of some_tensor: {some_tensor.shape}")
print(f"Device of some_tensor: {some_tensor.device}")
print(f"Size of some_tensor: {some_tensor.size()}")

Data Type of somme_tensor:  torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device of some_tensor: cpu
Size of some_tensor: torch.Size([3, 4])


### Manipulating tensors (Tensor Operations)

A link which i found useful: https://medium.com/@tushartripathi301997/pytorch-arithmetic-operations-and-matrix-ultiplication-49e14a624964

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication

In [51]:
# Create a Tensor
tensor =  torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [52]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [53]:
# Subtraction tensor by 10
tensor-10

tensor([-9, -8, -7])

In [54]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [55]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural netwroks and deep learning:
* Element wise
* Matrix Multiplication (Dot Product)
<br>**More information on matrix multiplication:** https://www.mathsisfun.com/algebra/matrix-multiplying.html
<br> There are two main rules that performing matrix multiplication needs to be satisfied:
1. The **Inner Dimension** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of **Outer Dimension** so:
* `(2,3) @ (3,2)` -> `(2,3) @ (3,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [56]:
# Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [58]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value) # checking the time used to solve matrix multplication by for loop 

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [59]:
%%time
torch.matmul(tensor, tensor) # checking time to solve matrix multiplication by using pytorch vectorization function

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [60]:
# Practicing by creating a big tensor and multiplying them
example_tensor1= torch.rand(2,2,2)
example_tensor1

tensor([[[0.9185, 0.8526],
         [0.3778, 0.0887]],

        [[0.4744, 0.8913],
         [0.1118, 0.0188]]])

In [61]:
example_tensor2= torch.rand(2,2,2)
example_tensor2

tensor([[[0.8337, 0.7001],
         [0.5592, 0.7928]],

        [[0.2657, 0.3204],
         [0.6983, 0.8918]]])

In [62]:
%%time
value_example = 0
for i in range(len(example_tensor1)):
    value_example += value_example *example_tensor1[i]*example_tensor2[i]
print(value_example)

tensor([[0., 0.],
        [0., 0.]])
CPU times: total: 0 ns
Wall time: 986 μs


In [63]:
%%time
torch.matmul(example_tensor1, example_tensor2)

CPU times: total: 0 ns
Wall time: 14.7 ms


tensor([[[1.2426, 1.3189],
         [0.3646, 0.3348]],

        [[0.7484, 0.9469],
         [0.0428, 0.0526]]])

### One of the most common errors in deep learning is shape error

In [64]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]]) #shape is (3x2)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]]) #shape is (3x2)

In [65]:
#torch.mm(tensor_A, tensor_B) # torch.mm(,) is same as toch.matmul(,)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#lets check the shape of tensors and find out why we are not able to multiply the tensors
tensor_A.shape , tensor_B.shape

to fix our tensor shape issues, we can manipulate the shape of one our tensors using a **TRANSPOSE**
A **Transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T # .T makes is transpose and turned it into (2x3)

In [ ]:
#lets check the transpose shape
tensor_B.T.shape

In [ ]:
# now we can multiply
print(torch.matmul(tensor_A,tensor_B.T))
print(f"Shape of new Matrix: {torch.matmul(tensor_A,tensor_B.T).shape}")

### Finding the min, max, mea, sum, etc (Tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x
print(f"x data type: {x.dtype}")

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean NOTE: We have to use Float type in mean so to change data type you can use.type() function
# **E.g: x.type(torch.float64)**

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> resturns the index of the min value in the tensor
torch.argmin(x),x.argmin()

In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> resturns the index of the max value in the tensor
torch.argmax(x),x.argmax()

In [ ]:
# Now lets see what is the min and max value that we got on the index 
x[0] , x[9]

## Reshaping, stacking, squeezing and unsqueezing tensors
* **Reshaping** - Reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of certain shape but keep the memory as the original tensor
* **Stacking** - Combine multiple tensors on top of each other(eg: vstack) or side-by-side(eg:hstack)
* **Squeezing** - Removes all `1` dimensions from a tensor
* **Unsqueeze** - add `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
# Lets create a tensor
y = torch.arange(0,100,2.5)
y, y.shape, y.dim()

In [ ]:
# Add an extra dimension
# y_reshaped = y.reshape(2,40)  # will give error because the tensor size is 40 and if we create from 2 to 40 it wil be 39
y_reshaped = y.reshape(1,40)
# y_reshaped = y.reshape(40,1) # will also but the shape will change to (40,1)
y_reshaped,y_reshaped.shape, y_reshaped.dim() #we can see that the dimension of the tensor has now changed to 2

In [66]:
# Change the view
z = y.view(1,40) # it works similar to the .reshape() but ther is a small difference
# z = y.view(40,1)
z, z.shape

NameError: name 'y' is not defined

In [ ]:
# Changeing Z changes X (because a view of a tensor shares the same memory as the original input)
# lets try to change value of tensor z and check if y changes or not
print(f"Value of z at second position: {z[0, 1]} and Value of y at second position: {y[1]}")
print("Now changing the value of z = 5 ")
z[0,1] = 5
print(f"Value of z at second position: {z[0, 1]} and Value of y at second position: {y[1]}") # it is changed now

In [ ]:
# Stack tensors on top of each other
y_stacked = torch.stack([y,y,y,y], dim=0) # you can change dimension depending upon the dimension of Y
y_stacked, y_stacked.shape

In [67]:
# Squeezing the tensors - it removes the single dimension in the tensor 
# Creating the tensor in which it is having 1 dimension
t = torch.rand(2,1,2)
t_squeeze = t.squeeze() 
print(f"t tensor: {t}, t-tensor shape: {t.shape} , t_squeezed tensor: {t_squeeze}, t_squeezed tensor shape: {t_squeeze.shape}")

# You can see that the 1 dimension is removed from the tensor and new shape is (2,2)

t tensor: tensor([[[0.2121, 0.7155]],

        [[0.5486, 0.2521]]]), t-tensor shape: torch.Size([2, 1, 2]) , t_squeezed tensor: tensor([[0.2121, 0.7155],
        [0.5486, 0.2521]]), t_squeezed tensor shape: torch.Size([2, 2])


In [68]:
# Unsqueezing the tensor - it adds a single dimension to the tensor
t_unsqueeze = t_squeeze.unsqueeze(dim=0)  # You can change the dimension 
print(f"t_squeezed tensor: {t_squeeze}, t_squeezed tensor shape: {t_squeeze.shape} , t_unsqueezed tensor: {t_unsqueeze}, t_unsqueezed tensor shape: {t_unsqueeze.shape}")

t_squeezed tensor: tensor([[0.2121, 0.7155],
        [0.5486, 0.2521]]), t_squeezed tensor shape: torch.Size([2, 2]) , t_unsqueezed tensor: tensor([[[0.2121, 0.7155],
         [0.5486, 0.2521]]]), t_unsqueezed tensor shape: torch.Size([1, 2, 2])


In [69]:
# Permuting the tensor - Rearrange the tensor in a specified order. torch.permute and it works like the .view()
x_original = torch.rand(size=(224, 224,3))  # [height, width, colour channels]
print(f"Previous tensor: {x_original} ,Previous tensor shape: {x_original.shape}")
# permute the original tensor to rearrange the axis (or dim) order e.g: [color channel, height, width]
x_permute = x_original.permute(2,0,1)
print(f"new tensor: {x_permute} ,new tensor shape: {x_permute.shape}")

Previous tensor: tensor([[[0.1636, 0.7039, 0.4157],
         [0.3787, 0.6732, 0.3655],
         [0.0819, 0.7862, 0.3969],
         ...,
         [0.9061, 0.1425, 0.3961],
         [0.7800, 0.1431, 0.2416],
         [0.3247, 0.5223, 0.5497]],

        [[0.1685, 0.6395, 0.5157],
         [0.3427, 0.0168, 0.9115],
         [0.8503, 0.5320, 0.0290],
         ...,
         [0.2460, 0.2511, 0.2377],
         [0.3604, 0.7498, 0.7533],
         [0.3107, 0.1610, 0.5602]],

        [[0.7114, 0.9298, 0.3643],
         [0.6169, 0.1749, 0.5478],
         [0.5821, 0.8768, 0.6738],
         ...,
         [0.5274, 0.2773, 0.7424],
         [0.3152, 0.5677, 0.2424],
         [0.3469, 0.0969, 0.7799]],

        ...,

        [[0.5741, 0.8579, 0.5985],
         [0.9494, 0.0553, 0.4140],
         [0.7485, 0.5476, 0.6991],
         ...,
         [0.5281, 0.1279, 0.3822],
         [0.4884, 0.8641, 0.7906],
         [0.4446, 0.2353, 0.1669]],

        [[0.2959, 0.7244, 0.3860],
         [0.8284, 0.4901, 0.58

## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [70]:
# Create a Tensor
x = torch.arange(1,19).reshape(2,3,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [71]:
# Lets index on our new tensor
x[0][1][2]

tensor(6)

### Pytorch Tensors and Numpy 

Numpy is a popular scientific Python numerical computing Library. https://numpy.org/
and becuse of this, PyTorch has functionality to interact with it.
*Data in Numpy,want in PyTorch tensor -> ``torch.from_numpy(ndarray)`
PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [72]:
import numpy as np  # importing numpy library

In [73]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # Warning: When converting from Numpy -> PyTorch, PyTorch reflects numpy´s default dtype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
array.dtype

dtype('float64')

In [75]:
tensor.dtype

torch.float64

In [76]:
# If we change anything in array  will it be changed in tensor as well ?
array = array  + 1
array, tensor
# NOTE: It didn´t change anything in tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
# Tensor to Numpy array
tensor = torch.zeros(2,8) # using .zero() or ones() will make a tensor of zeros or one
tensor, tensor.shape

(tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]),
 torch.Size([2, 8]))

In [78]:
# Now changing tensor to Numpy
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.shape

(array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 (2, 8))

In [79]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor +2
tensor, numpy_tensor
# Result shows it doesn´t share memory as well

(tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2., 2., 2., 2.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32))

## Reproducibilty (Trying to take random out of random)

In short how a neural network learns:
<br>`Start with random number -> tensors operations -> update random numbbers to try and make them of the data -> again -> again -> again..`
<br> To reduce the randomnessin neural networks and PyTorch come the concept of a **random seed**  https://docs.pytorch.org/docs/stable/notes/randomness.html
<br> Essentially what the random seed does is **Flavour** the randomness.

In [80]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) #checking if the values are equal in both random tensors

tensor([[0.0718, 0.5035, 0.9528, 0.0226],
        [0.6422, 0.2827, 0.5259, 0.7548],
        [0.9558, 0.7492, 0.7992, 0.6982]])
tensor([[0.0044, 0.6138, 0.9152, 0.6776],
        [0.7342, 0.1554, 0.6742, 0.4076],
        [0.2497, 0.0465, 0.3228, 0.1256]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
# Lets make some random but reproducinle tensors

# Set the random seed
random_seed = 10  # change the value of random_seed if you want to change the values in random tensors

torch.manual_seed(random_seed) # You have to feed rendom_seed value in torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)  # You have to call this function everytime you want to create a new random tensor with reproducibilty
random_tensor_D = torch.rand(3,4)

print(random_tensor_C) 
print(random_tensor_D)
print(random_tensor_C == random_tensor_D) #checking if the values are equal in both random tensors

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tensors and PyTorch Objects on GPU´s (Making faster computations)


### 1. Getting a GPU
1. `Use your own GPU - Takes a little bit of setup and requires the investment on GPU`
2. `Use cloud computing - GCP, AWS, AZURE, these services allow you to rent computers on the cloud and access them`

For 1 and 2 PyTorch + GPU driver(CUDA) takes a little bit of setting up, to do this. refer to PyTorch setup documentation. https://pytorch.org/

In [82]:
!nvidia-smi

Sat Jun  7 03:11:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.07                 Driver Version: 566.07         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   48C    P8              3W /   80W |    1365MiB /   8188MiB |     29%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with PyTorch


In [83]:
# check for GPU access with PyTorch
torch.cuda.is_available()

True

In [84]:
print(torch.__version__)

2.5.1+cu121


For PyTorch since it´s capable of running compute on the GPU or CPU, it´s best practice is to setup device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

In [85]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [86]:
# Count number of devices
torch.cuda.device_count()

1

In [87]:
# print('GPU name:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no GPU available")
# print('GPU name:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no GPU available")
# !nvidia-smi
# import torch
# print("PyTorch version:", torch.__version__)
# print("CUDA in PyTorch:", torch.version.cuda)
# print("Is CUDA available:", torch.cuda.is_available())
# import sys
# print(sys.version)
# import sys
# print(sys.executable)
# print(sys.version)

## to check the GPU is being used or not

## 3. Putting tensors (and Models) on the GPU
The reason is we want our tensors/models on the GPU is because usinng a GPU results in faster computations.

In [88]:
 # Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device ="cpu" )  # default is cpu

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [89]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [90]:
# If tensor is on GPU, can´t transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [91]:
# We have to convert tensor to CPU . So we will use tensor.cpu

In [92]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### EXERCISES AND EXTRA CURRICULUM
<br> see the link for exercises till we have done in the notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [93]:
# Create a random tensor with shape (7, 7).
ex_tensor = torch.rand(7,7)
ex_tensor

tensor([[0.7041, 0.5573, 0.6959, 0.9849, 0.2924, 0.4823, 0.6150],
        [0.4967, 0.4521, 0.0575, 0.0687, 0.0501, 0.0108, 0.0343],
        [0.1212, 0.0490, 0.0310, 0.7192, 0.8067, 0.8379, 0.7694],
        [0.6694, 0.7203, 0.2235, 0.9502, 0.4655, 0.9314, 0.6533],
        [0.8914, 0.8988, 0.3955, 0.3546, 0.5752, 0.4787, 0.5782],
        [0.7536, 0.1093, 0.4771, 0.1076, 0.9829, 0.1483, 0.5956],
        [0.3634, 0.7842, 0.5017, 0.4497, 0.8660, 0.9567, 0.1371]])

In [94]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
ex_tensor2 = torch.rand(1,7)
ex_tensor2
# now multiplying both tensors
mul_ten = torch.matmul(ex_tensor,ex_tensor2.t())
mul_ten # multiplied

tensor([[2.1734],
        [0.3989],
        [2.0813],
        [2.4314],
        [2.0367],
        [1.6660],
        [2.6003]])

In [95]:
#Set the random seed to 0 and do exercises 2 & 3 over again.
random_seed = 0
torch.manual_seed(random_seed)
ex_tensor = torch.rand(7,7)
print(ex_tensor) 

torch.manual_seed(random_seed)
ex_tensor2 = torch.rand(1,7)
print(ex_tensor2)

# now multiplying both the tensors 
mul_ten_rand =torch.matmul(ex_tensor,ex_tensor2.t())
mul_ten_rand

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [96]:
### Complete other questions as well CURRENTLY I AM MOVING TO THE TUTORIAL 